# Generated by Django 4.0.4 on 2022-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profile_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='<django.db.models.fields.related.OneToOneField>', max_length=20, verbose_name='Имя'),
        ),
    ]
