# Generated by Django 4.0.4 on 2022-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_orders_items_ordered_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='owner',
            field=models.CharField(blank=True, max_length=20, verbose_name='Заказчик(Username)'),
        ),
    ]
