# Generated by Django 4.0.4 on 2022-06-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_orders_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='delivered',
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_text',
            field=models.TextField(max_length=255, verbose_name='Текст'),
        ),
    ]
