# Generated by Django 4.0.4 on 2022-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_goods_delivered_alter_feedbacks_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=25, verbose_name='Имя(id заказчика)'),
        ),
    ]
