# Generated by Django 4.0.4 on 2022-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя(id заказчика)'),
        ),
    ]
