# Generated by Django 4.0.4 on 2022-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_feedbacks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='owner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заказчик(Username)'),
        ),
    ]
