# Generated by Django 4.0.4 on 2022-06-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_orders_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заказчик(Username)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя(id заказчика)'),
        ),
    ]
