# Generated by Django 4.0.4 on 2022-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_feedbacks_name_alter_orders_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Имя(id заказчика)'),
        ),
    ]
