# Generated by Django 4.0.4 on 2022-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(db_index=True, max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_ordered',
            field=models.TextField(blank=True, max_length=255, verbose_name='id`s товаров'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='owner',
            field=models.TextField(blank=True, max_length=255, verbose_name='Заказчик(Username)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(max_length=255, verbose_name='Имя(id заказчика)'),
        ),
    ]
