# Generated by Django 4.0.4 on 2022-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_name_alter_feedbacks_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(db_index=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_ordered',
            field=models.TextField(blank=True, verbose_name='id`s товаров'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='owner',
            field=models.TextField(blank=True, verbose_name='Заказчик(Username)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(verbose_name='Имя(id заказчика)'),
        ),
    ]
