# Generated by Django 4.0.4 on 2022-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_ordered',
            field=models.TextField(verbose_name='id`s товаров'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='owner',
            field=models.TextField(verbose_name='Заказчик(Username)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(verbose_name='Конечная стоимость товаров'),
        ),
    ]
